# Generated by Django 4.1.4 on 2023-01-03 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brand', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='country',
            name='country_name',
            field=models.CharField(default='india', max_length=100),
        ),
    ]
