# Generated by Django 4.1.5 on 2023-01-07 11:31

import brand.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brand', '0002_alter_country_country_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Suggestions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('suggestionCode', models.CharField(default=brand.models.generate_unique_code, max_length=5, unique=True)),
                ('drugCode', models.CharField(default='', max_length=5, unique=True)),
                ('Approved', models.BooleanField(default=False)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('names', models.TextField(null=True)),
            ],
        ),
    ]
