# Generated by Django 4.1.5 on 2023-01-09 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brand', '0003_suggestions'),
    ]

    operations = [
        migrations.AddField(
            model_name='suggestions',
            name='country_name',
            field=models.CharField(default='india', max_length=100),
        ),
        migrations.AddField(
            model_name='suggestions',
            name='listOfString',
            field=models.CharField(default='', max_length=100),
        ),
    ]
