# Generated by Django 4.1.5 on 2023-01-10 12:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('brand', '0004_suggestions_country_name_suggestions_listofstring'),
    ]

    operations = [
        migrations.RenameField(
            model_name='suggestions',
            old_name='listOfString',
            new_name='suggestionString',
        ),
    ]
