# Generated by Django 4.1.5 on 2023-01-11 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brand', '0005_rename_listofstring_suggestions_suggestionstring'),
    ]

    operations = [
        migrations.AddField(
            model_name='suggestions',
            name='inputType',
            field=models.TextField(default='listOfString'),
        ),
        migrations.AddField(
            model_name='suggestions',
            name='inputTypePreference',
            field=models.TextField(default='listOfStringMolecular'),
        ),
    ]
